name: Build & Test

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]



jobs:
  build_and_test:
    runs-on: sas-github-runner
    steps:
      - uses: actions/checkout@v4
      - name: Build & Test
        uses: ./.github/actions/build_and_test
