name: Deploy to Test, Preview Prod deploy and Validate

on:
  pull_request_review:
    branches: [main]
    types: [submitted]

jobs:
  deploy_to_test_and_preview_deploy_to_prod:
    uses: christianeriksson/cicd-workflows/.github/workflows/validate-on-approval-pre-merge.yml@main
    secrets: inherit
    with:
      deployments: >
        [
          {
            "directory": "."
          }
        ]