name: Verify in UAT

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    environment: verification
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to production environment
        uses: ./.github/actions/verify-in-test
